### ISSUE TITLE
Add szip support

### ISSUE THREAD

**Issue by dwr-psandhu** [conda-forge/hdf5-feedstock#120]
Issue: szip is a compression module available in the HDF5 distribution . Please enable it

Enabling it should be fairly straightforward if using cmake by adding this flow
-D HDF5_ENABLE_S_LIB_SUPPORT:BOOL=ON

**Comment by scopatz** [comment]
PRs welcome!

**Comment by jakirkham** [comment]
I thought there were licensing issues.

**Comment by scopatz** [comment]
Yeah, here is the statement: https://support.hdfgroup.org/doc_resource/SZIP/Commercial_szip.html

**Comment by dwr-psandhu** [comment]
@scopatz @jakirkham There is szip support in your pypi h5 package for windows :)
Here is the other issue on this https://github.com/ContinuumIO/anaconda-issues/issues/11382

I noticed that there are two dll files from hdf5 that are included in the pip install of h5py but not in the conda install.
Also the conda install of h5py depends upon hdf5 conda package but not h5py from pip.

**Comment by scopatz** [comment]
Hi @dwr-psandhu - yeah the conda packages are totally separate from the PyPI ones and we don't control how those are built at all, nor the conda packages that Anaconda provides. We really only manage what is on the conda-forge channel.

**Comment by dwr-psandhu** [comment]
Hi @scopatz ,  I was able to make a recipe that simply uses the hdf5 source with the default options ( which includes szip) and create a package that works. 
The fix like I suggested is really simple and I can certainly do a PR. However given the license issue you raise, are you willing to merge it or should I just close this issue?

**Comment by scopatz** [comment]
My read on this is that we can package it (non-comercial, scientific usage is allowed)

**Comment by jakirkham** [comment]
How can we ensure people are using the package under those conditions though? Alternatively how does a commercial user of this package avoid breaking those terms if we include it by default?

**Comment by scopatz** [comment]
A couple of thoughts:

1. The license for HDF5 does allow for decoding of szip by comercial entities. It only disallows encoding. Also comercial entities can have the encoding software... they just can't use it.
2. It isn't our job per se to do license compliance for users. There are lots of orgs that don't want to use GPL etc. and there are many unique OTHER licenses that disallow certain classes of users, some of which we package.  I agree that this is annoying to deal with and if we wanted to make things super safe for downstream users we'd have a variant. 

I don't think it is forbbidden for us to distribute an SZip-enabled HDF5 based on the license. It is more about how easy/safe/default we want to make that. I don't have much of an opinion there either way.

**Comment by kmilos** [comment]
I think this can now be enabled via [libaec](https://github.com/conda-forge/libaec-feedstock) that also ships its [own szip implementation](https://gitlab.dkrz.de/k202009/libaec/-/blob/master/README.SZIP) under a more permissive license

**Comment by adamcpovey** [comment]
I think I've gotten HDF5 to link against libaec simply by adding `--with-szlib="${PREFIX}"` to the configure command and that dependency to host and run in `meta.yaml` but this feedstock has a much more complicated recipe than this lowly scientist is comfortable editing.

For cmake, I needed to specify `-DSZIP_LIBRARY:FILEPATH=${PREFIX}/lib/libsz.a -DSZIP_INCLUDE_DIR:PATH=${PREFIX}/include`

**Comment by hmaarrfk** [comment]
Don't let that scare you too much.

Follow zlib and add the dependency you need.

Then update the associated build location shells.

https://github.com/conda-forge/hdf5-feedstock/blob/5913d3f2fe02905be1b910abf1daf9283c079545/recipe/meta.yaml#L77
