### ISSUE TITLE
Upgrade to version 1.12

### ISSUE THREAD

**Issue by djhoese** [conda-forge/hdf5-feedstock#121]
HDF5 1.12 has been out for a couple months and I was wondering what it would take to update the conda-forge package to this version? If there was a discussion for this somewhere else, sorry I couldn't find it.

https://www.hdfgroup.org/2020/03/release-of-hdf5-1-12-0-newsletter-172/

**Comment by scopatz** [comment]
Yeah, I guess this recipe didn't get picked up by the bot for some reason (@CJ-Wright @beckermr).  Feel free to put in a PR to this repo to add it!

**Comment by djhoese** [comment]
I was specifically interested in the S3 VFD support which I think requires `--enable-ros3-vfd` to be added to the configure phase. I was hoping if that was all that was needed that it could be included in the version update. If it takes more then I can open another issue and/or start a PR to add it.

**Comment by scopatz** [comment]
Feel free to put it in the same PR!
