### ISSUE TITLE
Not correctly finding zlib on Windows

### ISSUE THREAD

**Issue by patricksnape** [conda-forge/hdf5-feedstock#15]
As noted by @gillins on [netcdf](https://github.com/conda-forge/libnetcdf-feedstock/pull/1#issuecomment-221122139), the zlib referenced by the `hdf5-targets.cmake` file is incorrect. This can seen by the warning that is thrown by HDF5 [here](https://ci.appveyor.com/project/conda-forge/hdf5-feedstock/build/1.0.24/job/wnj9irpqex898ya6#L647). We need to make sure the correct zlib is being picked up as other packages that link to HDF5 may also fail due to this - see [here](https://github.com/conda-forge/libnetcdf-feedstock/pull/1#issuecomment-221122139).

**Comment by jakirkham** [comment]
Is this still an issue? Sounds like it was an issue with HDF5 1.8.15.x and it doesn't seem to occur with 1.8.16. @gillins, could you please let us know if this is still an issue or if this is resolved?

**Comment by gillins** [comment]
This seems to be fixed in the latest `hdf5` package.

**Comment by sdebionne** [comment]
It looks like this issue is back in 1.10.5 build 1003:

```
LINK : fatal error LNK1181: cannot open input file 'C:\bld\hdf5_split_1566414186589\_h_env\Library\lib\z.lib'
```

**Comment by ocefpaf** [comment]
> It looks like this issue is back in 1.10.5 build 1003:

Do you mean `1103`? I could not find `1003` in the main channel.

BTW, can you open a new issue? Old issues may have the same symptom but completely difference causes. A new issue help us debug it faster.

**Comment by sdebionne** [comment]
Sorry, yes, build 1103. Opening a new issue now.
