### ISSUE TITLE
MacOS Fortran shared libraries

### ISSUE THREAD

**Issue by hhslepicka** [conda-forge/hdf5-feedstock#151]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I am working on a project that uses `libhdf5hl_fortran` and I realized from looking into this feedstock that the Fortran shared libraries are not being build.
While I have no problem depending on both `hdf5` and `hdf5-static`, it would be great to have the shared library available as well.

I came across this comment https://github.com/conda-forge/hdf5-feedstock/pull/69#issuecomment-301680333 from 2017 and before I go down the rabbit hole of try to remove the patch and build shared libraries for Fortran I decided to check if that is something that the maintainers of this feedstock would like to see done.

Thank you

**Comment by hhslepicka** [comment]
Pinging @conda-forge/hdf5

**Comment by jakirkham** [comment]
conda-forge was in a different place 4 years ago. Would recommend just trying a new PR and seeing if we can get it to work. Is this something you'd be willing to pick up? 🙂

**Comment by hhslepicka** [comment]
@jakirkham I would like to take a stab at it... thanks for reply. I will get a PR up soon.
