### ISSUE TITLE
HDF5 CMake targets

### ISSUE THREAD

**Issue by JDuffeyBQ** [conda-forge/hdf5-feedstock#153]
The HDF5 CMake targets changed between 1.10.5 and 1.10.6.

- 1.10.5
  - hdf5::hdf5-shared
- 1.10.6
  - hdf5-shared

Defining the CMake variable HDF_PACKAGE_NAMESPACE to "hdf5::" restores the old namespace.

**Comment by hmaarrfk** [comment]
Do we still want this now that 1.12 has been released without the cmake variable defined?

**Comment by hmaarrfk** [comment]
It might be that this is causing the issues with finding HDF5 automatically on OSX.

**Comment by hmaarrfk** [comment]
hmm, well i'll lets see how the 1.14 migration is going. I'm not sure we are seeing this particular issue anymore
