### ISSUE TITLE
Issues with the strings function in Linux systems. 

### ISSUE THREAD

**Issue by varlackc** [conda-forge/hdf5-feedstock#154]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Ther is a build error on some Linux systems:
```
testlibinfo.sh: strings: commnd not found
```

**Comment by varlackc** [comment]
There is a pull request #155 that addresses this issue. 

https://github.com/conda-forge/hdf5-feedstock/pull/155

Please review and let me know if any additional changes are needed.

**Comment by hmaarrfk** [comment]
i'm confused as to how to recreate the issue? Is it still happening?
