### ISSUE TITLE
1.10.x+osx+Fortran: possible?

### ISSUE THREAD

**Issue by MarDiehl** [conda-forge/hdf5-feedstock#159]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:
I am trying to build a package for Linux and MacOS. Due to dependencies of other packages, I'm forced to use HDF5 1.10.x. Unfortunately, this package is build without Fortran libraries. Is it possible to rebuild the old 1.10.6 version with support for Fortran? The 1.12.1 version has Fortran support already.

**Comment by hmaarrfk** [comment]
I hope you found a way around your issue. Typically there isn't a strong incentive to build older packages here. It is a ALOT of maintenance work.

You should be able to define the HDF5 API version you use and much the of the API is actually kept for backward compatibility.

**Comment by hmaarrfk** [comment]
You can try to make a PR to the 1.10.x branch like I did, but people seem pretty swamped to review new features 😄 
https://github.com/conda-forge/hdf5-feedstock/pull/161

**Comment by MarDiehl** [comment]
@hmaarrfk: many thanks for the reply. In the meantime, 1.12.x is also working, no need for backports
