### ISSUE TITLE
OpenSSL 1 build?

### ISSUE THREAD

**Issue by mkitti** [conda-forge/hdf5-feedstock#194]
### Comment:

Would it possible to get a build that links against openssl 1 rather than openssl 3?

**Comment by hmaarrfk** [comment]
For our education, what is your usecase?

@conda-forge-admin please rerender

xref: https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/3838

**Comment by hmaarrfk** [comment]
I'm going to warn you that we recently closed the openssl 1 builds. So this will become increasingly harder.

I typically ask that people help maintain for these special requests, but given that you helped get down to the bottom of the ROS3 issue, i'll oblige since it is rather "easy" to do now.

**Comment by hmaarrfk** [comment]
and if you had any input https://github.com/conda-forge/libnetcdf-feedstock/pull/161 that would be greatly appreciated!

**Comment by mkitti** [comment]
Julia upstream uses OpenSSL 1.1.1

Julia binary packaging repackages the conda-forge package:
https://github.com/JuliaBinaryWrappers/HDF5_jll.jl

This is because Julia binary packaging normally relies on cross compilation, but HDF5 cross compilation requires configuration settings from the actual hardware. This probably could be extracted from the compiler toolchain, but no one has finished this work yet.

Julia will eventually have to resolve this when OpenSSL 1.1.1 support ends.
cc: @giordano @simonbyrne

**Comment by hmaarrfk** [comment]
Understood. i mean, we have "officially" ended support for openssl 1.1.1 by removing it from the build matrix https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/3838#issuecomment-1404001691

**Comment by jakirkham** [comment]
cc @conda-forge/core (because of OpenSSL 1.1.1 & Julia support)

**Comment by beckermr** [comment]
Feedstock maintainers are free to add local pins in their own conda_build_config.yaml if they want to maintain those pins. In this case, I'd ask that those who need those pins (i.e. the Julia Binary repackaging team) take responsibility for the additional maintenance. I'd also ask that the openssl 3 pin not be removed in order to minimize the effects on other users.
