### ISSUE TITLE
Feedstocks that build both HDF5 1.12.2 and 1.14.0

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/hdf5-feedstock#199]
### Comment:

Due to some concerns with HDF5 1.14.0 some feedstocks have decided to not move forward with the migration.

This has caused me to build some feedstocks with both HDF5 1.14.0 and 1.12.2 (the last version before 1.14.0 at conda forge)

* https://github.com/conda-forge/opencv-feedstock/pull/354
* https://github.com/conda-forge/vigra-feedstock/pull/109

If more conflicts arise, I might be interested in building:
* https://github.com/conda-forge/pytables-feedstock/

xref: https://github.com/conda-forge/libnetcdf-feedstock/pull/165

I'm keeping this list so that I know remember to undo the changes in the future.

**Comment by ijpulidos** [comment]
Not sure if related, but we are facing some problems with our macOS CI when we changed to HDF5 1.14.0, we had to pin the CI environment to use 1.12.2 for it to succeed in https://github.com/choderalab/openmmtools/pull/659/commits/1cdf490c57f7c876cef4b80e26993d0ddc6b3ac4 . Please let me know if this is relevant or if I should open a new issue with this information. Thanks!

**Comment by hmaarrfk** [comment]
here i am mostly keeping track of systems that work with both. It is a bit of "churn" to keep both maintained. Now that the libnetcdf maintainers have moved forward with the migration, I'm inclined to remove support for both versions of HDF5 in the feedstocks I maintain.

I think you should open a new issue to focus on your challenges. That will be the best way to get your questions answered.

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

lets drop 1.12.2 from our support matrix now that most have moved forward
