### ISSUE TITLE
@conda-forge-admin, please update version

### ISSUE THREAD

**Issue by Krande** [conda-forge/hdf5-feedstock#214]
### Additional comment:

Hey @hmaarrfk, I hope it's OK I checked for a new release this way. I am eager to test the new hdf5 version released yesterday given that it's supposed to fix the `H5T__init_native_float_types` issue we're seeing in https://github.com/conda-forge/code-aster-feedstock/pull/57

Btw. the latest hdf5 tagged release name differs slightly since the previous release ([hdf5-1_14_3](https://github.com/HDFGroup/hdf5/releases/tag/hdf5-1_14_3)  ->[hdf5_1.14.4](https://github.com/HDFGroup/hdf5/releases/tag/hdf5_1.14.4). So not sure if this stops the hdf5 feedstock in picking up the latest release or not?

**Comment by hmaarrfk** [comment]
A PR would be appreciated. Thanks!
