### ISSUE TITLE
gzip unavailable

### ISSUE THREAD

**Issue by pelson** [conda-forge/hdf5-feedstock#3]
@ericdill wrote:

Hi All,

I am running into an issue with the h5py and hdf5 packages from anaconda.org/conda-forge.  It appears that the gzip compression filter is not behaving properly, as I am getting exceptions in my test suite if I use h5py and hdf5 from anaconda.org/conda-forge.
```
Packages from conda-forge:
    h5py:            2.6.0-np110py34_1             conda-forge 
    hdf5:            1.8.16-0                      conda-forge 

Errors are:

    ValueError: Compression filter "gzip" is unavailable   
```
And the relevant travis-ci log: https://travis-ci.org/NSLS-II/suitcase/jobs/119284041

If I remove conda-forge from my ~/.condarc and install h5py and hdf5 from anaconda.org then my test suite is happy again.

Relevant travis-ci log for working build after I comment out conda-forge in my condarc: https://travis-ci.org/NSLS-II/suitcase/builds/119289079

I would imagine that this is a problem with the conda-forge h5py and hdf5 packages?

Not really sure what to do here... 

Thoughts?

Best,

Eric

**Comment by jakirkham** [comment]
Should be fixed in this PR ( https://github.com/conda-forge/hdf5-feedstock/pull/5 ).

**Comment by jakirkham** [comment]
FWIW, Windows shouldn't have this problem as it [finds zlib]( https://ci.appveyor.com/project/conda-forge/hdf5-feedstock/build/1.0.2/job/65mwwo1cv6o0v5yb#L410 ); however, we still need to fix its build.
