### ISSUE TITLE
The copyright notice (COPYING) is not included in the conda package

### ISSUE THREAD

**Issue by tylere** [conda-forge/hdf5-feedstock#33]
The HDF5 package's Notice and License Terms found in the [COPYING](https://www.hdfgroup.org/ftp/HDF5/current/src/unpacked/COPYING) file indicate that:

> 1. Redistributions of source code must retain the above copyright notice, 
>    this list of conditions, and the following disclaimer.

**Comment by jakirkham** [comment]
So we actually do include this in the package thanks to this [line]( https://github.com/conda-forge/hdf5-feedstock/blob/16cfa8bfb7fb2a638b800335d4b95a88b2e65f8a/recipe/meta.yaml#L104 ). I just pulled down a package and can see this license is included. Please let us know if there are instances where that is not the case.

**Comment by jakirkham** [comment]
Should add it is called `LICENSE.txt` and is in `info` in the extracted package IIRC.

**Comment by tylere** [comment]
When I install the hdf5 package, I cannot find the file COPYING (see below). I would guess that in addition to referring to it in the meta.yaml file, you need to explicitly copy it over, similar to what is done in the [zlib-feedstock](https://github.com/conda-forge/zlib-feedstock/blob/master/recipe/build.sh#L13) recipe.

$ find /opt/conda/pkgs/hdf5-1.8.15.1-2/ -name *COPYING*

$ cat /opt/conda/pkgs/hdf5-1.8.15.1-2/info/files 
bin/gif2h5
bin/h52gif
bin/h5c++
bin/h5cc
bin/h5copy
bin/h5debug
bin/h5diff
bin/h5dump
bin/h5import
bin/h5jam
bin/h5ls
bin/h5mkgrp
bin/h5perf_serial
bin/h5redeploy
bin/h5repack
bin/h5repart
bin/h5stat
bin/h5unjam
include/H5ACpublic.h
include/H5AbstractDs.h
include/H5Apublic.h
include/H5ArrayType.h
include/H5AtomType.h
include/H5Attribute.h
include/H5Classes.h
include/H5CommonFG.h
include/H5CompType.h
include/H5Cpp.h
include/H5CppDoc.h
include/H5Cpublic.h
include/H5DOpublic.h
include/H5DSpublic.h
include/H5DataSet.h
include/H5DataSpace.h
include/H5DataType.h
include/H5DcreatProp.h
include/H5Dpublic.h
include/H5DxferProp.h
include/H5EnumType.h
include/H5Epubgen.h
include/H5Epublic.h
include/H5Exception.h
include/H5FDcore.h
include/H5FDdirect.h
include/H5FDfamily.h
include/H5FDlog.h
include/H5FDmpi.h
include/H5FDmpio.h
include/H5FDmulti.h
include/H5FDpublic.h
include/H5FDsec2.h
include/H5FDstdio.h
include/H5FaccProp.h
include/H5FcreatProp.h
include/H5File.h
include/H5FloatType.h
include/H5Fpublic.h
include/H5Gpublic.h
include/H5Group.h
include/H5IMpublic.h
include/H5IdComponent.h
include/H5Include.h
include/H5IntType.h
include/H5Ipublic.h
include/H5LTpublic.h
include/H5Library.h
include/H5Location.h
include/H5Lpublic.h
include/H5MMpublic.h
include/H5Object.h
include/H5Opublic.h
include/H5PLextern.h
include/H5PLpublic.h
include/H5PTpublic.h
include/H5PacketTable.h
include/H5Ppublic.h
include/H5PredType.h
include/H5PropList.h
include/H5Rpublic.h
include/H5Spublic.h
include/H5StrType.h
include/H5TBpublic.h
include/H5Tpublic.h
include/H5VarLenType.h
include/H5Zpublic.h
include/H5api_adpt.h
include/H5overflow.h
include/H5pubconf.h
include/H5public.h
include/H5version.h
include/hdf5.h
include/hdf5_hl.h
lib/libhdf5.la
lib/libhdf5.settings
lib/libhdf5.so
lib/libhdf5.so.10
lib/libhdf5.so.10.0.1
lib/libhdf5_cpp.la
lib/libhdf5_cpp.so
lib/libhdf5_cpp.so.10
lib/libhdf5_cpp.so.10.0.1
lib/libhdf5_hl.la
lib/libhdf5_hl.so
lib/libhdf5_hl.so.10
lib/libhdf5_hl.so.10.0.1
lib/libhdf5_hl_cpp.la
lib/libhdf5_hl_cpp.so
lib/libhdf5_hl_cpp.so.10
lib/libhdf5_hl_cpp.so.10.0.1

**Comment by jakirkham** [comment]
We never built `1.8.15.1` at conda-forge. That's probably coming from `defaults` or somewhere else. May want to check where it is coming from. If it is coming from `defaults`, this issue should be raised [here]( https://github.com/ContinuumIO/anaconda-recipes/issues ).

**Comment by tylere** [comment]
Thanks for the clarification.

**Comment by jakirkham** [comment]
Of course. Though I agree with your concern that we need ensure licenses are included. Honestly I'm about to suggest in our next meeting that we simply always require license files unless upstream doesn't provide them (e.g. `setuptools`).
