### ISSUE TITLE
hdf5 is built without zlib

### ISSUE THREAD

**Issue by 183amir** [conda-forge/hdf5-feedstock#4]
from <https://circleci.com/gh/conda-forge/hdf5-feedstock/2>:
```
checking zlib.h usability... no
checking zlib.h presence... no
checking for zlib.h... no
checking for szlib... suppressed

============================
 zip_perf  Test Log
============================
No compression IO performance because zlib was not configured
```

**Comment by pelson** [comment]
That would be the reason for https://github.com/conda-forge/hdf5-feedstock/issues/3 too.

**Comment by jakirkham** [comment]
So, the OP's link is in a PR build. That being said, Linux master has the same problem. However, Mac [does not]( https://travis-ci.org/conda-forge/hdf5-feedstock/builds/118419662#L556-L557 ).

**Comment by jakirkham** [comment]
Should be fixed in this PR ( https://github.com/conda-forge/hdf5-feedstock/pull/5 ).

**Comment by jakirkham** [comment]
I think the reason Mac worked is that brew is including stuff that we are using again. That is why it did not affect Linux. Really need to fix this issue ( https://github.com/conda-forge/conda-smithy/issues/103 ).
