### ISSUE TITLE
Issue with placeholder path

### ISSUE THREAD

**Issue by astrofrog** [conda-forge/hdf5-feedstock#49]
A user reporting the following issue

```
ERROR: placeholder 'C:/conda/envs/_build' too short in:
hdf5-1.8.17-vc14_6
```

This happened when doing:

```
conda install -c conda-forge glueviz
```

on Windows.

**Comment by jakirkham** [comment]
Dup of issue ( https://github.com/conda-forge/hdf5-feedstock/issues/41 )?

**Comment by jakirkham** [comment]
Guessing this got solved with PR ( https://github.com/conda-forge/hdf5-feedstock/pull/56 ). Going to close it out. If it is still an issue, please feel free to let us know.
