### ISSUE TITLE
Link problems on Windows for 1.8.17

### ISSUE THREAD

**Issue by jeromekelleher** [conda-forge/hdf5-feedstock#58]
When I try to link against HDF5 on Windows, I get unresolved externals errors like the following:
```
tree_sequence.obj : error LNK2001: unresolved external symbol H5T_NATIVE_INT32_g
tree_sequence.obj : error LNK2001: unresolved external symbol H5P_CLS_DATASET_CREATE_ID_g
tree_sequence.obj : error LNK2001: unresolved external symbol H5T_IEEE_F64LE_g
tree_sequence.obj : error LNK2001: unresolved external symbol H5T_NATIVE_DOUBLE_g
tree_sequence.obj : error LNK2001: unresolved external symbol H5T_NATIVE_UINT32_g
tree_sequence.obj : error LNK2001: unresolved external symbol H5T_C_S1_g
tree_sequence.obj : error LNK2001: unresolved external symbol H5T_STD_I8LE_g
tree_sequence.obj : error LNK2001: unresolved external symbol H5T_STD_I32LE_g
tree_sequence.obj : error LNK2001: unresolved external symbol H5T_STD_U32LE_g
tree_sequence.obj : error LNK2001: unresolved external symbol H5T_NATIVE_SCHAR_g
build\lib.win-amd64-3.5\_msprime.cp35-win_amd64.pyd : fatal error LNK1120: 11 unresolved externals
error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\x86_amd64\\link.exe' failed with exit status 1120
```

See [here](ci.appveyor.com/project/jeromekelleher/msprime/build/1.0.28#L146) for the full run on AppVeyor. 

This problem does not happen if I pin HDF5 to version 1.8.15 (i.e., there are no unresolved externals reported). This is similar to an issue I've been having with GSL over at  conda-forge/gsl-feedstock#15, and is possibly related.

I'll have a look to see if I can figure out what changed between the two versions. I'm not very good with windows coding though, so I thought I'd report the issue in case someone else knows what the problem is.

**Comment by jakirkham** [comment]
Which two versions? Sorry, I'm unclear on what you are using now.

**Comment by jeromekelleher** [comment]
I get the link problem with version 1.18.17 (the current version in conda-forge). The problem doesn't happen with version 1.18.15.

**Comment by jeromekelleher** [comment]
Following up on this a bit, it seems that the problem also occurs with the anaconda version of hdf5 1.8.17. It seems that the first version of hdf5 in conda-forge was 1.8.16, so I was pulling 1.8.15 from anaconda without realising it. The problem also exists in 1.8.16.

Does it seem likely then that this is an upstream problem (i.e., something that HDF5 did between v15 and v16) rather than a conda packaging issue? I'm pretty much at sea here, so any advice/pointers would be much appreciated.

**Comment by jeromekelleher** [comment]
This can be fixed by defining "H5_BUILT_AS_DYNAMIC_LIB" at compile time. ([source](github.com/conda-forge/gdal-feedstock/issues/25))

Closing.

**Comment by jakirkham** [comment]
This is more of a historic note at this point.

HDF5 actually states that one should set `H5_BUILT_AS_DYNAMIC_LIB` in [1.8.17]( https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/obtain51817.html ) and [1.8.16]( https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/obtain51816.html ). Though FWICT it has been the case [for a while]( https://lists.hdfgroup.org/pipermail/hdf-forum_lists.hdfgroup.org/2012-November/006274.html ). This can be done by simply passing `-DH5_BUILT_AS_DYNAMIC_LIB` along in the C/C++ flags; unless of course, some library is misbehaving and overriding the C/C++ flags.
