### ISSUE TITLE
build dependence on hdf5 leads to undifined reference errors # [win]

### ISSUE THREAD

**Issue by looooo** [conda-forge/hdf5-feedstock#60]
Problem occuring in this recipe https://github.com/looooo/FreeCAD_Conda/tree/experimenting/libMed, when building with windows. This is related to the zlib library, because if I build hdf5 without zlib support libMed builds.
https://github.com/conda-forge/hdf5-feedstock/blob/master/recipe/bld.bat#L8 setting -DHDF5_ENABLE_Z_LIB_SUPPORT:BOOL=OFF

The linking problems can be seen here: I have them only in german language. (error LNK2019: unresolved external symbol)
```
Bibliothek "src\medC.lib" und Objekt "src\medC.exp" werden erstellt.
LINK : warning LNK4098: Standardbibliothek "MSVCRT" steht in Konflikt mit anderen Bibliotheken; /NODEFAULTLIB:Bibliothek verwenden.
libhdf5.lib(H5Zdeflate.c.obj) : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "inflate" in Funktion "H5Z_filter_deflate".
libhdf5.lib(H5Zdeflate.c.obj) : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "inflateEnd" in Funktion "H5Z_filter_deflate".
libhdf5.lib(H5Zdeflate.c.obj) : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "compress2" in Funktion "H5Z_filter_deflate".
libhdf5.lib(H5Zdeflate.c.obj) : error LNK2019: Verweis auf nicht aufgel÷stes externes Symbol "inflateInit_" in Funktion "H5Z_filter_deflate".
```

**Comment by jakirkham** [comment]
So I do speak a bit of German, but it is a bit rusty. Any chance we can get the traceback in English? Understanding what MSVC is doing is challenging enough. 😂 Thanks for reporting.

**Comment by gillins** [comment]
I think you might need to add `zlib.lib` to your `HDF5_LIBRARIES` so it can find these symbols like this:
```
-DHDF5_LIBRARIES="%LIBRARY_PREFIX%\libhdf5.lib %LIBRARY_PREFIX%\zlib.lib" ^
```
Not sure though...

**Comment by looooo** [comment]
thanks for the hint, but this seems not to work:
```
-DHDF5_LIBRARIES="%LIBRARY_PREFIX%\lib\libhdf5.lib %LIBRARY_PREFIX%\lib\zlib.lib" ^
```

```
ninja: error: FindFirstFileExA(c:/users/fc-builder/miniconda3/conda-bld/libmed_1490434332036/_b_env/library/lib/libhdf5.lib c:/users/fc-builder/miniconda3/conda-bld/libmed_1490434332036/_b_env/library/lib):
The filename, directory name, or volume label syntax is incorrect.
```

**Comment by looooo** [comment]
btw.: would it be possible to join two .libs to have the zlib.lib directly included in the hdf5.lib?

**Comment by gillins** [comment]
Your path is wrong.  Take out the `lib` part - `LIBRARY_PREFIX` should be all you need.

**Comment by looooo** [comment]
sorry, same error. The destination of the libraries is for sure %LIBRARY_PREFIX%\lib\

**Comment by looooo** [comment]
Using the shared library (dll) would be the better solution. But also there is something wrong:
```
C:\Users\fc-builder\Miniconda3\conda-bld\libmed_1490455196327\_b_env\Library\bin\hdf5.dll : fatal error LNK1107: Ung³ltige oder beschõdigte Datei: Lesen bei 0x340 nicht m÷glich.
```
en: LNK1107: invalid or corrupt file:

ps.: I have tried to use english language, but somhow this has overwritten my keyboard layout.

**Comment by looooo** [comment]
with a ";" as seperator this is working now. Thanks @gillins and @jakirkham .
https://github.com/looooo/FreeCAD_Conda/blob/experimenting/libMed/bld.bat#L4
