### ISSUE TITLE
Update HDF5 ecosystem to 1.8.18

### ISSUE THREAD

**Issue by qwhelan** [conda-forge/hdf5-feedstock#71]
After merging https://github.com/conda-forge/hdf5-feedstock/pull/68, I realized that almost all ```conda-forge``` packages have pinned their recipes to ```1.8.17|1.8.17.*```. As ```hdf5``` is cautious and checks that version numbers are the same for headers and shared objects, we'll need to update the pinned versions to allow a user to use ```1.8.18```.

I identified all ```conda-forge``` packages using ```hdf5``` by checking out https://github.com/conda-forge/feedstocks, running ```git submodule init && git submodule update```, and then executing the following:

    grep hdf5 * -R | awk -F/ '{print $1}' | sort | uniq > hdf5.txt

I will be creating PRs for each library below and checking them off as they get merged:
- [ ] alps https://github.com/conda-forge/alps-feedstock/pull/13
- [ ] armadillo
- [x] bob.io.base https://github.com/conda-forge/bob.io.base-feedstock/pull/20
- [x] caffe https://github.com/conda-forge/caffe-feedstock/pull/28
- [x] calliope https://github.com/conda-forge/calliope-feedstock/pull/4
- [x] casacore https://github.com/conda-forge/casacore-feedstock/pull/4
- [ ] cdo
- [x] cyclus https://github.com/conda-forge/cyclus-feedstock/pull/21
- [x] cyclus-build-deps https://github.com/conda-forge/cyclus-build-deps-feedstock/pull/9
- [x] flann https://github.com/conda-forge/flann-feedstock/pull/12
- [x] gdal https://github.com/conda-forge/gdal-feedstock/pull/157
- [x] gmt  https://github.com/conda-forge/gmt-feedstock/pull/6
- [ ] graph https://github.com/conda-forge/graph-feedstock/pull/1
- [x] h5py https://github.com/conda-forge/h5py-feedstock/pull/23
- [x] hdf5 https://github.com/conda-forge/hdf5-feedstock/pull/68
- [x] hdfeos5 https://github.com/conda-forge/hdfeos5-feedstock/pull/14
- [x] hyperion-fortran https://github.com/conda-forge/hyperion-fortran-feedstock/pull/7
- [x] itk https://github.com/conda-forge/itk-feedstock/pull/5
   - The one library pinned to ```1.8.*``` rather than ```1.8.17|1.8.17.*```
- [x] kealib https://github.com/conda-forge/kealib-feedstock/pull/11
- [x] libcdms https://github.com/conda-forge/libcdms-feedstock/pull/3
- [x] libcf https://github.com/conda-forge/libcf-feedstock/pull/6
- [x] libmatio https://github.com/conda-forge/libmatio-feedstock/pull/10
- [x] libnetcdf https://github.com/conda-forge/libnetcdf-feedstock/pull/21
- [ ] marray https://github.com/conda-forge/marray-feedstock/pull/2
- [x] moab https://github.com/conda-forge/moab-feedstock/pull/6
- [x] ncl https://github.com/conda-forge/ncl-feedstock/pull/11
- [x] nco https://github.com/conda-forge/nco-feedstock/pull/37
- [x] netcdf4 https://github.com/conda-forge/netcdf4-feedstock/pull/32
- [x] opencv https://github.com/conda-forge/opencv-feedstock/pull/76
- [x] openmc https://github.com/conda-forge/openmc-feedstock/pull/8
- [x] pyne https://github.com/conda-forge/pyne-feedstock/pull/10
- [x] pytables https://github.com/conda-forge/pytables-feedstock/pull/15
- [x] vigra https://github.com/conda-forge/vigra-feedstock/pull/26
- [x] vtk https://github.com/conda-forge/vtk-feedstock/pull/32
- [x] yaafe https://github.com/conda-forge/yaafe-feedstock/pull/2

**Comment by gillins** [comment]
II don't know much about it, but I thought updating https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/pin_the_slow_way.py would achieve the same result in a more automated fashion. cc @ocefpaf @jakirkham

**Comment by jakirkham** [comment]
That would be the place to start. Yes the bot should do this, but it is broken of late.

Still we should first send a PR to that script and only then PR the feedstocks after the pinning change has been accepted.

**Comment by qwhelan** [comment]
@gillins Thanks for pointing that out - definitely looked for something like this but didn't see any traces of it in most feedstocks I sampled.

Handling the upstream pin in https://github.com/conda-forge/conda-forge.github.io/pull/394

**Comment by jakirkham** [comment]
Thank you for doing that @qwhelan and putting in the time to make all these PRs. It's definitely appreciated.

**Comment by jakirkham** [comment]
Are we good to close this out? I think everything either got rebuilt with 1.8.18, got rebuilt with 1.10.1, or is simply lagging behind.
