### ISSUE TITLE
HDF5 1.10.0

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/hdf5-feedstock#9]
[HDF5 1.10.0](https://www.hdfgroup.org/HDF5/release/obtain5110.html) was release a few weeks back.  It includes a number of new features as well as some backward incompatible changes with the 1.8.x library.  Any plans to package up this new version?

**Comment by jakirkham** [comment]
Yes, lots of cool features in there. 😄

Trying to decide if we should have two branches here or not as there as HDF5 1.8.x is still around. Though it is worth noting that we are still pinned to `1.8.15*` at conda-forge. 💭

So, even if we make the release, we won't be using it any time soon for other stuff unfortunately. 😦

**Comment by jjhelmus** [comment]
I would vote for a separate branch for the 1.8.x and 1.10.x versions.  HDF5 1.10.0 added a bunch of features but also broke both library and (some) file compatibility.  I expect that a 1.8.x library will be needed for some time and the HDF Group may even make further 1.8.x released.

**Comment by ocefpaf** [comment]
I agree with @jjhelmus.   I recommend updating master with the latest version and putting the 1.8.x in another branch.

**Comment by astrofrog** [comment]
This is I think a similar situation to PyQt in the defaults channel. What about going through with a script and making sure all conda-forge packages manually pin HDF5 to 1.8.*, then remove the global pinning, and then update this recipe to 1.10? Then packages can opt-in to 1.10 as needed.

**Comment by tschoonj** [comment]
Any movement on getting 1.10.x into conda-forge? It's become a bit of a nuisance not to have this package now that we are using SWMR files...

**Comment by zxweed** [comment]
Is there a way to build pytables with hdf5 11.10.1 package (that is available on conda-forge)? The pytables 3.4.2 requires hdf5 1.8.18-0 now..

**Comment by jjhelmus** [comment]
hdf5 1.10.1 is available on the `conda-forge` channel (thanks @ocefpaf).  Closing this issue.

@zxweed Your question about hdf5 1.10.1 and pytables would likely get a better response at the [pytables-feedstock](https://github.com/conda-forge/pytables-feedstock) repository.
